/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LED_Control_Reg.h>
#include <LED_0.h>
#include <LED_0_aliases.h>
#include <LED_1.h>
#include <LED_1_aliases.h>
#include <LED_2.h>
#include <LED_2_aliases.h>
#include <LED_3.h>
#include <LED_3_aliases.h>
#include <LED_4.h>
#include <LED_4_aliases.h>
#include <LED_5.h>
#include <LED_5_aliases.h>
#include <LED_6.h>
#include <LED_6_aliases.h>
#include <LED_7.h>
#include <LED_7_aliases.h>
#include <MISO.h>
#include <MISO_aliases.h>
#include <MOSI.h>
#include <MOSI_aliases.h>
#include <SCLK.h>
#include <SCLK_aliases.h>
#include <RadioController.h>
#include <SS.h>
#include <SS_aliases.h>
#include <Button.h>
#include <Button_aliases.h>
#include <LCD.h>
#include <RadioController_IntClock.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
