/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Service Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <D5_Yellow.h>
#include <D5_Yellow_aliases.h>
#include <D6_Red.h>
#include <D6_Red_aliases.h>
#include <ADC_SAR_Seq_1.h>
#include <A3.h>
#include <A3_aliases.h>
#include <D12.h>
#include <D12_aliases.h>
#include <Switch_Clock.h>
#include <D12_Button_State.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <ADC_SAR_Seq_1_intClock.h>
#include <ADC_SAR_Seq_1_IRQ.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <UART_SCBCLK.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>

/*[]*/

